print("Transfert de chaleur")
e1=input("Entrez la première épaisseur: ")
e2=input("Entrez dans la deuxième épaisseur: ")
L=input("Entrez la largeur L: ")
l1=input("Entrez la largeur de la première Brique: ")
l2=input("Entrez la largeur du vide: ")
Lmb=input("Etrez lambda de Brique: ")
Lmv=input("Entrez lambda de vide: ")
try:
    e1=float(e1)
    e2=float(e2)
    L=float(L)
    l1=float(l1)
    l2=float(l2)
    Lmb=float(Lmb)
    Lmv=float(Lmv)

    Ra=(e2)/(Lmb+L+l1)
    print("la résistance A est", Ra)
    Rb=(e2)/(Lmv+L+l1)
    print("la résistance B est", Rb)
    l=l1+l2*2
    R1=(e1)/(Lmv+L+l)
    print("la résistance 1 est", R1)
    R2= (e2)/(Lmv+L+l)
    print("la résistance 2 est", R2)
except:
    print("erreur")
